# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aeaa34be65df8a5752b341610b80f8283775312f4e42391a30ea51a648c44095c1671755378a95255ecd2a1be883bd7acad625e7313b3a1c603338610f9e46cf

test:
  secret_key_base: 5b50b87f57536917958234bcf818922f096f3014119dca8b9f110ec69148563df274e982078bb1eac16ae50ae65aa7a42607fad55cf6506ffb13e64c88ed1eae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
